[Server]
ServerOn=0
GameServPort=5622
DenialPort=5623

[Client]
;Theme=800
Theme=1024
ShowMiniskill=1
CanOpenUrlWhenExit=0
FullScreen=0
Represent=2
FPS=0
DynamicLight=0
CapPath=.\pic
KeepOutSide=1
AwardPosition=-1
Bil_StartAuto=0

[Launcher]
profile=0
